### ISSUE TITLE
Using : instead of @

### ISSUE THREAD

**Issue by milesj** [css-modules/icss#1]
First off, love the idea behind this spec. It seems to be very well thought out and something we should strive to achieve.

However, one thing really stood out, is that the spec is using `:` instead of `@` for its structures, for example, `:import` compared to `@import`. It looks like an at-rule @ would be a far better choice, as it has built in functionality for such a use case, like:
- [Error handling](http://www.w3.org/TR/css-syntax-3/#error-handling), which allows for backwards compatibility
- [Parsing rules](http://www.w3.org/TR/css-syntax-3/#parse-a-list-of-rules0) designed specifically for at-rules

At-rules seem to be the go to for such functionality that "defines", for example: `@charset`, `@font-face`, `@keyframes`, etc.

Is the only reason for avoiding at-rules is that `@import` has already been taken? It seems like it would be a great opportunity to extend `@import` and provide a super-set of functionality.

``` css
@import "path/to/dep.css" {
  localAlias: keyFromDep;
  /* ... */
}
```

**Comment by pygy** [comment]
Indeed, that sounds like the right thing to do.

It may be useful to see how current browsers handle these `@import <path> <block>` forms.

**Comment by geelen** [comment]
One of the guiding principles when working with CSS Modules & ICSS is that we needed syntax that could pass through the existing landscape of preprocessors and browsers without breaking anything, so that people could gently opt-in to the new features. Consider the way `var x = require('y')` and `module.exports = z` didn't break anything in JS that previously existed. Given the use of `@import` and `@include` and the fact that LESS borks on arbitrary `@` rules, we had to choose something that all those tools see as inert. The pseudo-selector usage of `:import` and `:export` is a semantic misappropriation, for sure, but it's the most pragmatic choice.

Happy to hear more objections & suggestions though :)

**Comment by davidkpiano** [comment]
@geelen I feel like there should be more focus on keeping the same semantics as CSS, rather than doing something non-semantic just so that preprocessors don't choke on it (that's an uphill battle that will always be lost, haha).

The two semantic items I'd like to see most in ICSS are:
- At-rules for describing blocks
- Properties _only_ for specifying visual properties of selected elements. (this is important!)

**Comment by geelen** [comment]
Care to expand on that last point?

**Comment by geelen** [comment]
Gonna close this for lack of activity. I'd be happy to continue the discussion though!
